default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: lunch_ordering_development

test:
  <<: *default
  database: lunch_ordering_test

production:
  <<: *default
  database: lunch_ordering_production
  username: lunch_ordering
  password: <%= ENV['LUNCH_ORDERING_DATABASE_PASSWORD'] %>
